# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7741a7211f0c421dfc3bf54914fb421da8b30adaabb4a431b2221f5b141ba88fdf5dac8011759ea96a39e0d41973630873404d2fd39cace6188911a7e8740c2a

test:
  secret_key_base: d81bbb4fc3c5a2761807b57bf7c17631124c5c33ffde29c9cd37f171d61f591eecf03425b503c517c05e10634d497f6ffe4f21fa476b173864a7512c4e8c91cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
